bdaypro/bdaypro/urls.py
from django.contrib import admin
from django.urls import path,include
from birthday import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path(r'',views.IndexView.as_view(),name='index'),
    path(r'admin/', admin.site.urls),
    path(r'birthday/',include('birthday.urls',namespace='birthday')),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

bdaypro/birthday/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'birthday'

urlpatterns = [
    path('create/',views.WishView.as_view(),name='wishlist'),
    path('',views.NameList.as_view(),name='viewlist'),
    path('<int:pk>/',views.BirthWishView.as_view(),name='birthlist'),
    # path('create/',views.SchoolCreateView.as_view(),name = 'create'),
    # path('update/<int:pk>/',views.SchoolUpdateView.as_view(),name= 'update'),
    # path('delete/<int:pk>/',views.SchoolDeleteView.as_view(),name= 'delete'),

]

bdaypro/birthday/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Birthwish(models.Model):
    name = models.CharField(max_length=256,unique=True)
    message = models.CharField(max_length=256)
    images = models.ImageField(upload_to='pic',blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("birthday:viewlist")

bdaypro/birthday/views.py
from django.shortcuts import render
from django.views.generic import View,TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView
from . import models
from django.urls import reverse

# Create your views here.
# SPUERUSER homebirth pwd homebirth 
class IndexView(TemplateView):
    template_name = 'index.html'


class WishView(CreateView):
    model = models.Birthwish
    fields = ('name','message','images')
    # success_url = reverse('birthday:IndexView')

class NameList(ListView):
    model = models.Birthwish
    # school_list ...return... 
    context_object_name = 'Birthwishs'
    # otherwise take auto school_list

class BirthWishView(DetailView):
    context_object_name = 'Births_detail'
    model = models.Birthwish
    template_name = 'birthday/Births_detail.html'

bdaypro/birthday/templates/birthday/Births_detail.html
{% extends "birthday/base.html" %}

{% block body_block %}
<div>

<marquee behavior='alternate' scrolldelay='10'><H5 style="color: blue;">thanks to  <b  style ='color:red'; >' {{Births_detail.name}} '</b> personally </H5></marquee></div>

<div class="jumbotron">
    <div class="card" style="width:200px">
        {% if Births_detail.images %}
        <img height="200px" class="card-img-top rounded" src="{{ Births_detail.images.url }}" alt="Card image">
        {% else %}
        {% load static %} <img height="200px" class="card-img-top rounded" src="{% static "1.jpg" %}" alt="Hi!" />
        {% endif %}
        <div class="card-body">
          <h4 class="card-title">{{Births_detail.name}} </h4>
          <p class="card-text">{{Births_detail.message}}</p>
          <a class="card-link" href="{% url 'index' %}">home </a> 
          <a class="card-link" href="{% url 'birthday:viewlist' %}">see others </a> 
        </div>
    </div>
</div>

{% endblock %}



<hr>

bdaypro/birthday/templates/birthday/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=
    , initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="{% static "bootstrap.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "style.css" %}">
</head>
<body>
  <nav class="navbar navbar-expand-sm bg-warning navbar-light sticky-top">
    
    <div class="container">
        <ul class="navbar-nav">
            <li><a class="nav-link" href="{% url 'index' %}">home </a> </li>
            <li><a class="nav-link" href="{% url 'birthday:wishlist' %}">Wish to.. </a> </li>
            <li><a class="nav-link" href="{% url 'birthday:viewlist' %}">see.. </a> </li>
            <li><a class="nav-link" href="{% url 'admin:index' %}">Admin</a>  </li>
                     
    </div>

</nav>

<div cl ass="container">

    {% block body_block %}
    <!-- Anything outside of this will be inherited if you extend -->
    {%  endblock %}
</div>




<!-- <script src="static/css_js/jquery-3.2.1.min.js"></script>
<script src="static/css_js/popper.js"></script> -->
<script src="{% static "bootstrap.min.js" %}"></script>     
</body>
</html>

bdaypro/birthday/templates/birthday/birthwish_form.html
{% extends "birthday/base.html" %}

{% block body_block %}
<h1>
    {% if not form.instance.pk %}
    Create Birthwish
</h1>
        <div class ='jumbotron'>
            
        <form method="post" class="form" enctype="multipart/form-data" >
        
        {% csrf_token %}
        {{ form.as_p }}
        
        <input type="submit" class='btn btn-primary' value="submit">
        
        </form>
    {% else  %}

    thanks for wishes..

    {% endif %}

<h6> image is optional... </h6>
<h6>if birthdday name is alredy exist try our fansy identify name.. </h6>
<h6>this is a testingof doployememnt so ...  hahaha</h6>
<h6>thanks for the wishes</h6>
</div>
{% endblock %}

bdaypro/birthday/templates/birthday/birthwish_list.html
{% extends "birthday/base.html" %}

{% block body_block %}
<div class="jumbotron">
    <h1 class="display-3">BIRTH WISHES </h1>
    <h3>click on name and see birthwishes</h3>
    <!-- <p class="lead">Jumbo helper text</p> -->
    <hr class="my-2">
    <p><ol>
        <div class="row">
        {% for wish in Birthwishs %}
        <div class=" col-sm-4">
          <div class="card text-left" style="width: 200pxs; margin-top: 10px;">
            {% load static %}
            <img height="200px" class="card-img-top" src="{% static "1.jpg" %}" alt="">
            <div class="card-body">
              <h4 class="card-title"><a href="{{ wish.id }}"> {{wish.name}} </a></h4>
              <p class="card-text">
        
        
              </p>
            </div>
          </div>
        </div>
        {% endfor %}
       </div>   
      </ol>
    </p>
</div>
<h1></h1>

{% endblock %}

bdaypro/birthday/templates/birthday/thanx.html
{% extends "birthday/base.html" %}

{% block body_block %}
{% load static %}
<div class="jumbotron">
    <h1 class="display-3">BIRTHDAY SPECIAL...</h1>
    <p class="lead">testing page...</p>
    <hr class="my-2">
    <!-- <p>today date is..</p> -->
    thanx too registered...
    <p class="lead">
        <a class="btn btn-primary btn-lg" href="{% url 'index' %}" role="button">back to home page.. </a>
    </p>
    
    {% load static %} <img src="{% static "2.gif" %}" alt="Hi!" />
    
</div>
{% endblock %}

bdaypro/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=
    , initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="{% static "bootstrap.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "style.css" %}">
</head>
<body>
  <nav class="navbar navbar-expand-sm bg-warning navbar-light sticky-top">
    
    <div class="container">
        <ul class="navbar-nav">
            <li><a class="nav-link" href="{% url 'basic_app:wishlist' %}">Wish to.. </a> </li>
            <li><a class="nav-link" href="{% url 'birthday:viewlist' %}">see.. </a> </li>
            <li><a class="nav-link" href="{% url 'admin:index' %}">Admin</a>  </li>
                     
    </div>

</nav>

<div cl ass="container">

    {% block body_block %}
    <!-- Anything outside of this will be inherited if you extend -->
    {%  endblock %}
</div>




<!-- <script src="static/css_js/jquery-3.2.1.min.js"></script>
<script src="static/css_js/popper.js"></script> -->
<script src="{% static "bootstrap.min.js" %}"></script>     
</body>
</html>

bdaypro/templates/index.html
{% extends "birthday/base.html" %}
{% load static %} 
{% block body_block %}
<header class="page-header">
<h1>
    <p id="demo" class="font-weight-lighter" ></p>
</h1>
</header>

<script>
// Set the date we're counting down to
var countDownDate = new Date("aug 9, 2020 00:00:00").getTime();

// Update the count down every 1 second
var x = setInterval(function() {

  // Get today's date and time
  var now = new Date().getTime();

  // Find the distance between now and the count down date
  var distance = countDownDate - now;

  // Time calculations for days, hours, minutes and seconds
  var days = Math.floor(distance / (1000 * 60 * 60 * 24));
  var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
  var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
  var seconds = Math.floor((distance % (1000 * 60)) / 1000);

  // Display the result in the element with id="demo"
  document.getElementById("demo").innerHTML = days + "d " + hours + "h "
  + minutes + "m " + seconds + "s ";

  // If the count down is finished, write some text
  if (distance < 0) {
    clearInterval(x);
    document.getElementById("demo").innerHTML = "HAPPY BIRTHDAY DANNY....";
  }
}, 1000);
</script>

<div class="jumbotron">
    <div class="row">
        <div class="col-sm-6">
            <img width="500px" src="{% static "4.gif" %}" alt="Hi!" />
        </div>

        <div class="col-sm-6">
            <h1 class="display-3">BIRTHDAY SPECIAL...</h1>            
        <p class="lead">
            <a class="btn btn-primary btn-lg" href="{% url 'birthday:wishlist' %}" role="button">Wish to Kshitij Bansod.. </a>
        </p>
        <p class="lead">testing page...</p>
        </div>
    </div>
    <img class="im" src="{% static "6.gif" %}" alt="Hi!" />
    
    <img class="im" src="{% static "3.gif" %}" alt="Hi!" />
    
    
    <img class="im" src="{% static "5.gif" %}" alt="Hi!" />
    
</div>
{% endblock %}